PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS Products (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Code TEXT NOT NULL UNIQUE,
    Name TEXT NOT NULL,
    PriceSatang INTEGER NOT NULL CHECK (PriceSatang BETWEEN 0 AND 100000000),
    StockQuantity INTEGER NOT NULL CHECK (StockQuantity BETWEEN 0 AND 1000000)
);

CREATE TABLE IF NOT EXISTS Carts (
    Id TEXT PRIMARY KEY NOT NULL,
    Status TEXT NOT NULL DEFAULT 'Open' CHECK (Status IN ('Open', 'CheckedOut')),
    CreatedAt TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS CartItems (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    CartId TEXT NOT NULL REFERENCES Carts(Id),
    ProductId INTEGER NOT NULL REFERENCES Products(Id),
    Quantity INTEGER NOT NULL CHECK (Quantity BETWEEN 1 AND 1000000),
    UNIQUE (CartId, ProductId)
);

CREATE TABLE IF NOT EXISTS Orders (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    CartId TEXT NOT NULL UNIQUE REFERENCES Carts(Id),
    TotalSatang INTEGER NOT NULL CHECK (TotalSatang >= 0),
    CreatedAt TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS OrderItems (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    OrderId INTEGER NOT NULL REFERENCES Orders(Id),
    ProductId INTEGER NOT NULL REFERENCES Products(Id),
    ProductCode TEXT NOT NULL,
    ProductName TEXT NOT NULL,
    UnitPriceSatang INTEGER NOT NULL CHECK (UnitPriceSatang >= 0),
    Quantity INTEGER NOT NULL CHECK (Quantity > 0),
    UNIQUE (OrderId, ProductId)
);
